# Generated by Django 5.1.3 on 2025-03-22 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_rename_date_update_product_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total_montant',
            new_name='total_sales',
        ),
        migrations.AddField(
            model_name='sale',
            name='method_payment',
            field=models.CharField(choices=[('CREDIT CARD', 'Card Bank'), ('CASH', 'Cash'), ('mobile_money', 'MOBILE MONEY')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='status_payment',
            field=models.CharField(choices=[('paid', 'PAID'), ('pending', 'En Attente')], default='PAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='describe of product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name of product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='price of articles', max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(choices=[('owner', 'Owner'), ('employee', 'Employee')], default='Admin', max_length=100),
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=500)),
                ('date_return', models.DateTimeField(auto_now=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.sale')),
            ],
        ),
    ]
