# Generated by Django 5.1.3 on 2025-03-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_rename_total_montant_sale_total_sales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_unit',
        ),
    ]
